[project]
name = "agno-study"
version = "0.1.0"
description = "Use the Agno agent framework to build an agent that can teach about birds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.5.10",
    "aiofiles>=24.1.0",
    "anthropic>=0.53.0",
    "bs4>=0.0.2",
    "fastapi>=0.115.12",
    "google-genai>=1.19.0",
    "groq>=0.26.0",
    "ollama>=0.5.1",
    "openai>=1.86.0",
    "pgvector>=0.4.1",
    "psycopg>=3.2.9",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.45.1",
]
